### ISSUE TITLE
Erreur en importation des détections

### ISSUE THREAD

**Issue by equinton** [inrae/filo-science#65]
[Thu Nov 18 10:39:32.983997 2021] [php7:error] [pid 15404] [client 195.221.113.195:49944] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Antenna::getIdFromCode() must be of the type string, null given, called in /var/www/html/filo-science/v1.10.0/modules/classes/import/function_type.class.php on line 359 and defined in /var/www/html/filo-science/v1.10.0/modules/classes/tracking/antenna.class.php:107\nStack trace:\n#0 /var/www/html/filo-science/v1.10.0/modules/classes/import/function_type.class.php(359): Antenna->getIdFromCode()\n#1 /var/www/html/filo-science/v1.10.0/modules/classes/import/function_type.class.php(54): FunctionType->getAntennaFromCode()\n#2 /var/www/html/filo-science/v1.10.0/modules/import/importExec.php(126): FunctionType->functionCall()\n#3 /var/www/html/filo-science/v1.10.0/framework/controller.php(565): include('/var/www/html/f...')\n#4 /var/www/html/filo-science/v1.10.0/index.php(27): include('/var/www/html/f...')\n#5 {main}\n  thrown in /var/www/html/filo-science/v1.10.0/modules/classes/tracking/antenna.class.php on line 107, referer: https://filo-eabx.irstea.fr/index.php?module=importExec

**Comment by equinton** [comment]
Pb de paramétrage de l'importation, pas du code.
